name: 'wechat-work'
on:
  schedule:
    - cron: '5 0 * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: notification-action
        uses: actions/checkout@v2
      - name: notification-action
        uses: guangzhengli/wecom-notification-action@main
        with:
          webhook: ${{ secrets.WECOM_WEBHOOK_KEY }}
          is_at_all: "false"
          type: "message"
          message: "每日问好：愿岁月静好，每日笑口常开"
