name: 'wecom/wechat-work robot notification action'

on:
  watch:
    types: [started]
  schedule:
    - cron: '5 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: wecom robot action
        uses: rcy1314/notification-action@main
        with:
          webhook: ${{ secrets.WECOM_WEBHOOK_KEY}}
          is_at_all: "false"
          type: "message"
          message: "每日问好：愿岁月静好，每日笑口常开"
