name: 'wecom/wechat-work robot notification action'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: wecom robot action
        uses: guangzhengli/wecom-notification-action@main
        with:
          webhook: ${{ secrets.WECOM_WEBHOOK_KEY}}
          is_at_all: "false"
          type: "message"
          message: "每日问好：愿岁月静好，每日笑口常开"
