name: 'wecom/wechat-work robot notification action'
on:
  schedule:
    - cron: '5 0 * * *'
    
bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          webhook: ${{ secrets.WECOM_WEBHOOK_KEY}}
          is_at_all: "false"
          type: "message"
          message: "每日问好：愿岁月静好，每日笑口常开"
